name: Create S3 Bucket

on: 
  workflow_dispatch:
    inputs:
      bucketname:
        description: 'Enter S3 bucketname'
        required: true

jobs:
    create-bucket:
      runs-on: ubuntu-latest
      steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create S3 bucket
        run: |
           aws s3 mb s3://${{ github.event.inputs.bucketname }}

            
